const FETCH_BOOKS_SUCCESS = 'BOOKS_LOADED';
const FETCH_BOOKS_REQUEST = 'BOOKS_REQUESTED';
const FETCH_BOOKS_FAILURE = 'BOOKS_ERROR';

export {
    FETCH_BOOKS_SUCCESS,
    FETCH_BOOKS_REQUEST,
    FETCH_BOOKS_FAILURE
};
