const FETCH_BOOKS_SUCCESS = 'BOOKS_LOADED';
const FETCH_BOOKS_REQUEST = 'BOOKS_REQUESTED';
const FETCH_BOOKS_FAILURE = 'BOOKS_ERROR';
const CART_ITEM_DELETE = 'CART_ITEM_DELETE';
const CART_ITEM_INCREASE = 'CART_ITEM_INCREASE';
const CART_ITEM_DECREASE = 'CART_ITEM_DECREASE';
const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';

export {
    FETCH_BOOKS_SUCCESS,
    FETCH_BOOKS_REQUEST,
    FETCH_BOOKS_FAILURE,
    CART_ITEM_DELETE,
    CART_ITEM_INCREASE,
    CART_ITEM_DECREASE,
    BOOK_ADDED_TO_CART
};
